esp_toml_version = 1.0

# This should be a publicly accessible URL of the file server where your firmware binaries are available for download
firmware_images_url = "https://ota.ling-qu.com/"

# Apps that you support and for which the binaries are available to publish. You can have multiple apps as a comma separated list
# The launch pad UI will automatically show these Apps in the available apps dropdown
# There should be a config section per listed App
supported_apps = ["aaaa"]


[YOUR_FIRMWARE_APP_NAME]
# ESP32 Chipsets for which you have a supported Firmware App. Define a property for each supported chipset in the given format.
chipsets = ["ESP32-C3"]
# Configure the name of the binary file
image.esp32-c3 = "target.bin"
# Optional: Phone APP URLs if any for Playstores
android_app_url = "bbbb"
ios_app_url = "wwww"
# Optional: URL of the Markdown file for additional information about the app
readme.text = "<URL to your Markdown file>"
# Optional: Supported console baudrate for app firmware (default value is 115200)
console_baudrate = 115200